# This compose file defines the external
# database that drizzle will connect to during development.

volumes:
  pgdata:
    name: pgdata

services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
