name: Setup Project Tools
description: Sets up all the project tools for building, testing and deploying the tool

inputs:
  pnpm-version:
    required: true
    description: The version of the PNPM package manager used in the project
  node-version:
    required: true
    description: The version of Node used in the project

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install
